# Generated by Django 5.1 on 2024-12-07 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='is_kyc_complete',
            field=models.BooleanField(default=False),
        ),
    ]
