# Generated by Django 5.1 on 2024-12-09 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankapp', '0002_userinfo_is_kyc_complete'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='is_kyc_complete',
        ),
        migrations.AddField(
            model_name='user',
            name='is_kyc_complete',
            field=models.BooleanField(default=False),
        ),
    ]
