# Generated by Django 5.1 on 2025-01-03 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankapp', '0004_remove_user_is_kyc_complete_userinfo_is_kyc_complete'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='account_id',
        ),
        migrations.RemoveField(
            model_name='account',
            name='red_code',
        ),
        migrations.AlterField(
            model_name='account',
            name='account_number',
            field=models.IntegerField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='account',
            name='pin_number',
            field=models.IntegerField(default=0, max_length=4),
        ),
    ]
