# Generated by Django 5.1 on 2025-01-08 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankapp', '0006_alter_account_account_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_number',
            field=models.IntegerField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='pin_number',
            field=models.IntegerField(default=0),
        ),
    ]
